add support for RFC5914 structs. make adjusts to some prior structure definitions to work around macro-related issues. Notes on non-use of macros
In trust_anchor_format.rs
- Choice was not used on TrustAnchorChoice owing to types not available in Asn1Type enum
- Sequence was not used on TrustAnchorInfo owing to lack of DecodeValue required by context_specific

error[E0277]: the trait bound `TrustAnchorInfo<'a>: DecodeValue<'_>` is not satisfied
   --> x509/src/trust_anchor_format.rs:295:22
    |
295 |                     .context_specific::<TrustAnchorInfo<'a>>(TAC_TA_INFO_TAG, TagMode::Explicit)?;
    |                      ^^^^^^^^^^^^^^^^ the trait `DecodeValue<'_>` is not implemented for `TrustAnchorInfo<'a>`
    |
note: required by a bound in `Decoder::<'a>::context_specific`
   --> der/src/decoder.rs:172:12
    |
172 |         T: DecodeValue<'a> + FixedTag,
    |            ^^^^^^^^^^^^^^^ required by this bound in `Decoder::<'a>::context_specific`

- Sequence was not used on CertPathControls to use decode_implicit for each field (trailing bits were left using the default decoder even with mods to Certificate and NameConstraints)

In certificate.rs
- Sequence was not used on Certificate due to same issue as described above for TrustAnchorInfo (i.e., tension between use of DecodeValue and Decodable)
- Sequence was not used on NameConstraints for the same DecodeValue vs Decodable issue.